### ISSUE TITLE
Snapshots of unexpected error messages are flaky

### ISSUE THREAD

**Issue by albertfdp** [albertfdp/unexpected-enzyme#4]
When the `to-have-props-satisfying` snapshot runs, it will output in one line sometimes, others in 2 lines, making the test unstable: https://github.com/albertfdp/unexpected-enzyme/commits/master/test/__snapshots__/to-have-props-satisfying.spec.js.snap

**Comment by sunesimonsen** [comment]
I'll try to look into it, but I I find it hard to believe that the error message should be changing the line breaks.

**Comment by sunesimonsen** [comment]
Ahh that is because you haven't hardcoded the unexpected error message line length. 

```js
unexpected.output.preferredWidth = 80;
```

It is because unexpected is smart enough to format the error message based on your console width :-) But that does not work when you need to test the output.

**Comment by sunesimonsen** [comment]
Just set that in the setup.

**Comment by albertfdp** [comment]
Ah! Makes sense, just fixed it

**Comment by sunesimonsen** [comment]
Great!
